
package br.com.cea.ebs.cea.ecommerce.order.wevo.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OrderWevo_Service", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/order/wevo/v1", wsdlLocation = "file:/C:/work/cea/workspace/java/OrderService/WebContent/WEB-INF/wsdl/EBS/CeA/ecommerce/OrderWevo1.wsdl")
public class OrderWevoService
    extends Service
{

    private final static URL ORDERWEVOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.cea.ebs.cea.ecommerce.order.wevo.v1.OrderWevoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.cea.ebs.cea.ecommerce.order.wevo.v1.OrderWevoService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/work/cea/workspace/java/OrderService/WebContent/WEB-INF/wsdl/EBS/CeA/ecommerce/OrderWevo1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/work/cea/workspace/java/OrderService/WebContent/WEB-INF/wsdl/EBS/CeA/ecommerce/OrderWevo1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERWEVOSERVICE_WSDL_LOCATION = url;
    }

    public OrderWevoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWevoService() {
        super(ORDERWEVOSERVICE_WSDL_LOCATION, new QName("http://www.cea.com.br/EBS/CEA/ecommerce/order/wevo/v1", "OrderWevo_Service"));
    }

    /**
     * 
     * @return
     *     returns OrderWevoPortType
     */
    @WebEndpoint(name = "OrderWevo_Service")
    public OrderWevoPortType getOrderWevoService() {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/order/wevo/v1", "OrderWevo_Service"), OrderWevoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWevoPortType
     */
    @WebEndpoint(name = "OrderWevo_Service")
    public OrderWevoPortType getOrderWevoService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/order/wevo/v1", "OrderWevo_Service"), OrderWevoPortType.class, features);
    }

}
