
package br.com.cea.ebs.cea.ecommerce.tracking.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.com.cea.ebo.cea.v1.MetaInfType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Tracking_PortType", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/tracking/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.cea.ebo.cea.ecommerce.tracking.v1.ObjectFactory.class,
    br.com.cea.ebo.cea.v1.ObjectFactory.class,
    br.com.cea.ebs.cea.ecommerce.tracking.v1.ObjectFactory.class
})
public interface TrackingPortType {


    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns br.com.cea.ebs.cea.ecommerce.tracking.v1.TrackingResponse
     * @throws TechnicalFaultMsg
     * @throws BusinessFaultMsg
     */
    @WebMethod(operationName = "Tracking")
    @WebResult(name = "TrackingResponse", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/tracking/v1", partName = "parameters")
    public TrackingResponse tracking(
        @WebParam(name = "TrackingRequest", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/tracking/v1", partName = "parameters")
        TrackingRequest parameters,
        @WebParam(name = "MetaInformacao", targetNamespace = "http://www.cea.com.br/EBO/CEA/v1", header = true, partName = "header")
        MetaInfType header)
        throws BusinessFaultMsg, TechnicalFaultMsg
    ;

}
