
package br.com.cea.ebs.cea.ecommerce.cartaopl.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.com.cea.ebo.cea.v1.MetaInfType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CartaoPL_PortType", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.cea.ebs.cea.ecommerce.cartaopl.v1.ObjectFactory.class,
    br.com.cea.ebo.cea.v1.ObjectFactory.class
})
public interface CartaoPLPortType {


    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns br.com.cea.ebs.cea.ecommerce.cartaopl.v1.CartaoPLResponse
     * @throws TechnicalFaultMsg
     * @throws BusinessFaultMsg
     */
    @WebMethod(operationName = "CartaoPL")
    @WebResult(name = "CartaoPLResponse", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", partName = "parameters")
    public CartaoPLResponse cartaoPL(
        @WebParam(name = "CartaoPLRequest", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", partName = "parameters")
        CartaoPLRequest parameters,
        @WebParam(name = "MetaInformacao", targetNamespace = "http://www.cea.com.br/EBO/CEA/v1", header = true, partName = "header")
        MetaInfType header)
        throws BusinessFaultMsg, TechnicalFaultMsg
    ;

    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns br.com.cea.ebs.cea.ecommerce.cartaopl.v1.CartaoPLResponse
     * @throws TechnicalFaultMsg
     * @throws BusinessFaultMsg
     */
    @WebMethod(operationName = "CartaoPLLog")
    @WebResult(name = "CartaoPLResponse", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", partName = "parameters")
    public CartaoPLResponse cartaoPLLog(
        @WebParam(name = "CartaoPLLogRequest", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", partName = "parameters")
        CartaoPLLogRequest parameters,
        @WebParam(name = "MetaInformacao", targetNamespace = "http://www.cea.com.br/EBO/CEA/v1", header = true, partName = "header")
        MetaInfType header)
        throws BusinessFaultMsg, TechnicalFaultMsg
    ;

}
