
package br.com.cea.ebs.cea.ecommerce.cartaopl.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CartaoPL_Service", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", wsdlLocation = "file:/C:/work/cea/workspace/java/PaymentService/WebContent/WEB-INF/wsdl/EBS/CeA/ecommerce/CartaoPL.wsdl")
public class CartaoPLService
    extends Service
{

    private final static URL CARTAOPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.cea.ebs.cea.ecommerce.cartaopl.v1.CartaoPLService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.cea.ebs.cea.ecommerce.cartaopl.v1.CartaoPLService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/work/cea/workspace/java/PaymentService/WebContent/WEB-INF/wsdl/EBS/CeA/ecommerce/CartaoPL.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/work/cea/workspace/java/PaymentService/WebContent/WEB-INF/wsdl/EBS/CeA/ecommerce/CartaoPL.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARTAOPLSERVICE_WSDL_LOCATION = url;
    }

    public CartaoPLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartaoPLService() {
        super(CARTAOPLSERVICE_WSDL_LOCATION, new QName("http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", "CartaoPL_Service"));
    }

    /**
     * 
     * @return
     *     returns CartaoPLPortType
     */
    @WebEndpoint(name = "CartaoPL_Service")
    public CartaoPLPortType getCartaoPLService() {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", "CartaoPL_Service"), CartaoPLPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartaoPLPortType
     */
    @WebEndpoint(name = "CartaoPL_Service")
    public CartaoPLPortType getCartaoPLService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/cartaopl/v1", "CartaoPL_Service"), CartaoPLPortType.class, features);
    }

}
