
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.vtex_commerce_webapps_adminwcfservice.ArrayOfProductDTO;
import org.datacontract.schemas._2004._07.vtex_commerce_webapps_adminwcfservice.ArrayOfStockKeepingUnitDTO;
import org.datacontract.schemas._2004._07.wmi_domain_b2c_vtex.ArrayOfInvoiceConfirmDto;
import org.datacontract.schemas._2004._07.wmi_domain_b2c_vtex.ArrayOfInvoiceDto;
import org.datacontract.schemas._2004._07.wmi_domain_b2c_vtex.ArrayOfOrderDto;
import org.datacontract.schemas._2004._07.wmi_domain_business.ServiceResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IWmiService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.wmi_domain_business.ObjectFactory.class,
    org.tempuri.ObjectFactory.class,
    org.datacontract.schemas._2004._07.wmi_domain_b2c_vtex.ObjectFactory.class,
    org.datacontract.schemas._2004._07.vtex_commerce_webapps_adminwcfservice.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface IWmiService {


    /**
     * 
     * @param instanceId
     * @param productCollection
     * @return
     *     returns org.datacontract.schemas._2004._07.wmi_domain_business.ServiceResponse
     */
    @WebMethod(operationName = "ProductInsert", action = "http://tempuri.org/IWmiService/ProductInsert")
    @WebResult(name = "ProductInsertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProductInsert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductInsert")
    @ResponseWrapper(localName = "ProductInsertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductInsertResponse")
    public ServiceResponse productInsert(
        @WebParam(name = "instanceId", targetNamespace = "http://tempuri.org/")
        String instanceId,
        @WebParam(name = "productCollection", targetNamespace = "http://tempuri.org/")
        ArrayOfProductDTO productCollection);

    /**
     * 
     * @param skuCollection
     * @param instanceId
     * @return
     *     returns org.datacontract.schemas._2004._07.wmi_domain_business.ServiceResponse
     */
    @WebMethod(operationName = "SkuInsert", action = "http://tempuri.org/IWmiService/SkuInsert")
    @WebResult(name = "SkuInsertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SkuInsert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SkuInsert")
    @ResponseWrapper(localName = "SkuInsertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SkuInsertResponse")
    public ServiceResponse skuInsert(
        @WebParam(name = "instanceId", targetNamespace = "http://tempuri.org/")
        String instanceId,
        @WebParam(name = "skuCollection", targetNamespace = "http://tempuri.org/")
        ArrayOfStockKeepingUnitDTO skuCollection);

    /**
     * 
     * @param instanceId
     * @return
     *     returns org.datacontract.schemas._2004._07.wmi_domain_b2c_vtex.ArrayOfInvoiceDto
     */
    @WebMethod(operationName = "InvoiceGetNew", action = "http://tempuri.org/IWmiService/InvoiceGetNew")
    @WebResult(name = "InvoiceGetNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InvoiceGetNew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InvoiceGetNew")
    @ResponseWrapper(localName = "InvoiceGetNewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InvoiceGetNewResponse")
    public ArrayOfInvoiceDto invoiceGetNew(
        @WebParam(name = "instanceId", targetNamespace = "http://tempuri.org/")
        String instanceId);

    /**
     * 
     * @param listId
     * @param instanceId
     * @return
     *     returns org.datacontract.schemas._2004._07.wmi_domain_business.ServiceResponse
     */
    @WebMethod(operationName = "InvoiceConfirm", action = "http://tempuri.org/IWmiService/InvoiceConfirm")
    @WebResult(name = "InvoiceConfirmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InvoiceConfirm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InvoiceConfirm")
    @ResponseWrapper(localName = "InvoiceConfirmResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InvoiceConfirmResponse")
    public ServiceResponse invoiceConfirm(
        @WebParam(name = "instanceId", targetNamespace = "http://tempuri.org/")
        String instanceId,
        @WebParam(name = "listId", targetNamespace = "http://tempuri.org/")
        ArrayOfInvoiceConfirmDto listId);

    /**
     * 
     * @param instanceId
     * @return
     *     returns org.datacontract.schemas._2004._07.wmi_domain_b2c_vtex.ArrayOfOrderDto
     */
    @WebMethod(operationName = "OrderGetNew", action = "http://tempuri.org/IWmiService/OrderGetNew")
    @WebResult(name = "OrderGetNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OrderGetNew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OrderGetNew")
    @ResponseWrapper(localName = "OrderGetNewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OrderGetNewResponse")
    public ArrayOfOrderDto orderGetNew(
        @WebParam(name = "instanceId", targetNamespace = "http://tempuri.org/")
        String instanceId);

    /**
     * 
     * @param listOrderIdConfirmation
     * @param instanceId
     * @return
     *     returns org.datacontract.schemas._2004._07.wmi_domain_business.ServiceResponse
     */
    @WebMethod(operationName = "OrderConfirm", action = "http://tempuri.org/IWmiService/OrderConfirm")
    @WebResult(name = "OrderConfirmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OrderConfirm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OrderConfirm")
    @ResponseWrapper(localName = "OrderConfirmResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OrderConfirmResponse")
    public ServiceResponse orderConfirm(
        @WebParam(name = "instanceId", targetNamespace = "http://tempuri.org/")
        String instanceId,
        @WebParam(name = "listOrderIdConfirmation", targetNamespace = "http://tempuri.org/")
        ArrayOfstring listOrderIdConfirmation);

}
