CREATE TABLE merge_item_base_2_log(
    id_base_2 NUMBER PRIMARY KEY,
	id_pagamento  VARCHAR2(128) NOT NULL,
	create_date   DATE NOT NULL,
	id_pedido     CHAR(7) NOT NULL,
	xml			  VARCHAR2(4000) NOT NULL
);

CREATE TABLE merge_item_base_2(
    id_base_2 NUMBER PRIMARY KEY,
	id_pagamento  VARCHAR2(128) NOT NULL,
	create_date 	DATE NOT NULL,
	execution_date 	DATE,
	status 			NUMBER(2) NOT NULL,
	desctiption_status VARCHAR(255) NOT NULL,
	tp_reg      	CHAR(2) NOT NULL,
	dt_mov_log  	CHAR(8) NOT NULL,
	cd_fl       	CHAR(4) NOT NULL,
	cd_log_pos  	CHAR(2) NOT NULL,
	cd_vrs_pos  	CHAR(2) NOT NULL,
	cd_rls_vrs  	CHAR(2) NOT NULL,
	cd_mov_pos  	CHAR(2) NOT NULL,
	ide_opera   	CHAR(3) NOT NULL,
	pais        	CHAR(2) NOT NULL,
	tip_transac 	CHAR(1) NOT NULL,
	pln_credt   	CHAR(5) NOT NULL,
	tip_doc     	CHAR(1) NOT NULL,
	num_cartao  	CHAR(19) NOT NULL,
	num_docum   	CHAR(19),
	vlr_pago    	CHAR(13) NOT NULL,
	moeda       	CHAR(3) NOT NULL,
	id_pedido   	CHAR(7) NOT NULL,
	data_item		CHAR(8) NOT NULL,
	hora        	CHAR(6) NOT NULL,
	cod_superv  	CHAR(12) NOT NULL,
	flg_autoriz 	CHAR(1) NOT NULL,
	cod_orpag   	CHAR(3) NOT NULL,
	reas_code   	CHAR(3) NOT NULL,
	resp_code   	CHAR(1),
	cod_autoriz 	CHAR(6),
	flg_offline 	CHAR(1) NOT NULL,
	num_fone    	CHAR(20),
	loja        	CHAR(4) NOT NULL,
	vl_pago_din 	CHAR(13) NOT NULL,
	vl_pago_chq 	CHAR(13) NOT NULL,
	vl_pago_tef 	CHAR(13) NOT NULL,
	vl_pago_bns		CHAR(13) NOT NULL,
	vl_pago_uss		CHAR(13) NOT NULL,
	vl_pago_cqu 	CHAR(13) NOT NULL,
	tp_operacao 	CHAR(2) NOT NULL,
	num_ticket  	CHAR(9) NOT NULL,
	leit_cart   	CHAR(1) NOT NULL,
	num_operador	CHAR(3) NOT NULL,
	num_parc		CHAR(2) NOT NULL,
	reason_code   	CHAR(3),
	ret_code   		CHAR(3)
);

CREATE SEQUENCE sqn_merge_item_base_2_log MINVALUE 1 MAXVALUE 999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE sqn_merge_item_base_2 MINVALUE 1 MAXVALUE 999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE;