
package br.com.cea.ebs.cea.ecommerce.bankslip.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import br.com.cea.ebo.cea.v1.MetaInfType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BankSlip_PortType", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.com.cea.ebo.cea.v1.ObjectFactory.class,
    br.com.cea.ebs.cea.ecommerce.bankslip.v1.ObjectFactory.class
})
public interface BankSlipPortType {


    /**
     * 
     * @param parameters
     * @param header
     * @return
     *     returns br.com.cea.ebs.cea.ecommerce.bankslip.v1.BankSlipResponse
     * @throws BusinessFaultMsg
     * @throws TechnicalFaultMsg
     */
    @WebMethod(operationName = "BankSlip")
    @WebResult(name = "BankSlipResponse", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1", partName = "parameters")
    public BankSlipResponse bankSlip(
        @WebParam(name = "BankSlipRequest", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1", partName = "parameters")
        BankSlipRequest parameters,
        @WebParam(name = "MetaInformacao", targetNamespace = "http://www.cea.com.br/EBO/CEA/v1", header = true, partName = "header")
        MetaInfType header)
        throws BusinessFaultMsg, TechnicalFaultMsg
    ;

}
