
package br.com.cea.ebs.cea.ecommerce.bankslip.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BankSlip_Service", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1", wsdlLocation = "file:/C:/work/cea/workspace/java/EcommerceCore/wsdl/EBS/CeA/ecommerce/BankSlip.wsdl")
public class BankSlipService
    extends Service
{

    private final static URL BANKSLIPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.cea.ebs.cea.ecommerce.bankslip.v1.BankSlipService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.cea.ebs.cea.ecommerce.bankslip.v1.BankSlipService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/work/cea/workspace/java/EcommerceCore/wsdl/EBS/CeA/ecommerce/BankSlip.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/work/cea/workspace/java/EcommerceCore/wsdl/EBS/CeA/ecommerce/BankSlip.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANKSLIPSERVICE_WSDL_LOCATION = url;
    }

    public BankSlipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankSlipService() {
        super(BANKSLIPSERVICE_WSDL_LOCATION, new QName("http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1", "BankSlip_Service"));
    }

    /**
     * 
     * @return
     *     returns BankSlipPortType
     */
    @WebEndpoint(name = "BankSlip_Service")
    public BankSlipPortType getBankSlipService() {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1", "BankSlip_Service"), BankSlipPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankSlipPortType
     */
    @WebEndpoint(name = "BankSlip_Service")
    public BankSlipPortType getBankSlipService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/bankslip/v1", "BankSlip_Service"), BankSlipPortType.class, features);
    }

}
