
package br.com.cea.ebs.cea.ecommerce.affiliated.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Affiliated_Service", targetNamespace = "http://www.cea.com.br/EBS/CEA/ecommerce/affiliated/v1", wsdlLocation = "WEB-INF/wsdl/EBS/CeA/ecommerce/Affiliated.wsdl")
public class AffiliatedService
    extends Service
{

    private final static URL AFFILIATEDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.cea.ebs.cea.ecommerce.affiliated.v1.AffiliatedService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.cea.ebs.cea.ecommerce.affiliated.v1.AffiliatedService.class.getResource(".");
            url = new URL(baseUrl, "WEB-INF/wsdl/EBS/CeA/ecommerce/Affiliated.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/EBS/CeA/ecommerce/Affiliated.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AFFILIATEDSERVICE_WSDL_LOCATION = url;
    }

    public AffiliatedService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AffiliatedService() {
        super(AFFILIATEDSERVICE_WSDL_LOCATION, new QName("http://www.cea.com.br/EBS/CEA/ecommerce/affiliated/v1", "Affiliated_Service"));
    }

    /**
     * 
     * @return
     *     returns AffiliatedPortType
     */
    @WebEndpoint(name = "Affiliated_Service")
    public AffiliatedPortType getAffiliatedService() {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/affiliated/v1", "Affiliated_Service"), AffiliatedPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AffiliatedPortType
     */
    @WebEndpoint(name = "Affiliated_Service")
    public AffiliatedPortType getAffiliatedService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cea.com.br/EBS/CEA/ecommerce/affiliated/v1", "Affiliated_Service"), AffiliatedPortType.class, features);
    }

}
